FROM python:3.13.3-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

# Install system dependencies for PostgreSQL, LDAP, and SASL
RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
  python3-dev default-libmysqlclient-dev pkg-config \
  build-essential \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set up a non-root user
RUN useradd -U app_user && \
    install -d -m 0755 -o app_user -g app_user /app

# Set working directory
WORKDIR /app

# Copy the requirements file 
COPY requirements.txt /tmp/requirements.txt

# Update pip
RUN pip install --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt

# Copy project files and set permissions
COPY --chown=app_user:app_user . .

# Ensure shell scripts are executable
RUN chmod a+x docker/django/entrypoint.sh docker/django/start.sh

# Switch to non-root user
USER app_user:app_user

# Ensure media directory exists and is owned by app_user
RUN mkdir -p /app/media && chown -R app_user:app_user /app/media

# Set entrypoint
# Explicitly specify execution shell
ENTRYPOINT ["/bin/bash", "docker/django/entrypoint.sh"]
CMD [ "/bin/bash", "docker/django/start.sh", "backend" ]
